# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternative',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
        migrations.AddField(
            model_name='survey',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
    ]
