# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_auto_20170420_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='user_session',
            field=models.CharField(default='anonymus', max_length=255, null=True, verbose_name='Usuário'),
        ),
    ]
