# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_auto_20170420_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='user_session',
            field=models.CharField(max_length=255, verbose_name='Usuário'),
        ),
    ]
